version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php-app
    container_name: php-app-container
    restart: unless-stopped
    tty: true
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost
      DB_CONNECTION: sqlite
      
    working_dir: /var/www/html
      
    ports:
      - "8000:8000"
      
    volumes:
      - ./:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./path/to/your/database-file.sqlite:/var/www/html/database/database.sqlite
      
volumes:
  dbdata: